### ISSUE TITLE
Applied example error

### ISSUE THREAD

**Issue by cbrnr** [lindeloev/shiny-rt#3]
Thanks for this great tutorial! I tried running the applied code example on my local machine, but I get a very unspecific error:

```
> fit <- brm(formula=rt ~ condition + (1|id),
+            dat=data, 
+            family=shifted_lognormal(),
+            file='fit_slog')
Compiling the C++ model
Start sampling

SAMPLING FOR MODEL 'e07756ee2fd6b5fa71a0e4c57facb23a' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 0.006012 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 60.12 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
[1] "Error in sampler$call_sampler(args_list[[i]]) : " "  c++ exception (unknown reason)"                
error occurred during calling the sampler; sampling not done
```

Maybe I'm missing some required packages, but I couldn't find what I need to install (in addition to `brms`, `tidyverse`, and `rtdists`).

**Comment by lindeloev** [comment]
My guess is that you cannot run other models with `brms` either? [Copy-pasting the error message into Google](https://www.google.com/search?q=error+in+sampler%24call_sampler(args_list%5B%5Bi%5D%5D)+%3A+%22+%22+c%2B%2B+exception+(unknown+reason)&rlz=1C1GGRV_enDK766DK771&oq=error+in+sampler%24call_sampler(args_list%5B%5Bi%5D%5D)+%3A+%22+%22++c%2B%2B+exception+(unknown+reason)&aqs=chrome..69i57.2958j0j7&sourceid=chrome&ie=UTF-8) suggests that this is a compiler-issue that arises on MacOS systems. This is a bit out of my scope, but if you find a solution with this link, it would be great if you could write it here for others to see.

**Comment by cbrnr** [comment]
Thanks for the link, I have never used `brms` before so I don't know. I justed wanted to run the example, but it seems like this is very involved on macOS and I don't have time to look into it just for the example. I'll just switch to my Linux machine 😄.
