### ISSUE TITLE
Possible typo in section 4.2

### ISSUE THREAD

**Issue by jackdolgin** [lindeloev/shiny-rt#5]
This repository is an incredible resource! I wanted to ask about line 917 of `index.Rmd`, which currently reads as:

> Because $\mu$ and $\sigma$ define the *log*-normal distribution, they are on a log scale. This means that we expect a median RT of $ndt + exp(\mu) = 0.17 + exp(-0.69) = 0.50$ seconds for condition "accuracy" (the intercept), and a median RT of `exp(-0.69 -0.40) = 0.34` seconds for condition "speed". If you get confused about these transformations, worry not. `brms` has you covered, no matter the distribution:

I just wanted to double check about the equations-- specifically that .50 should be the sum of the first equation, and the second equation shouldn't instead equal .17 + exp(-0.69 -0.40). Thanks for such a great job already!

**Comment by lindeloev** [comment]
You are right! Will rebuild HTML + reupload to shinyapps soon
